In [20]:
import numpy as np

a = np.arange(1,5)
print(a.shape)
print(a)

print(a[:,None].shape)
print(a[:,None])

print(a[None,:].shape)
print(a[None,:])

print(np.reshape(a, (-1, 1)))
print(np.reshape(a, (1, -1)))



(4,)
[1 2 3 4]
(4, 1)
[[1]
 [2]
 [3]
 [4]]
(1, 4)
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
