In [34]:
import numpy as np
import pickle

nlist = [1,2,3]
narray = np.array([1,2,3])

print(nlist)
print(narray)
print(type(nlist))
print(type(narray))
print(nlist +  nlist)
print(narray + narray)


# matriy can be initialiyed with bothe ölist and narrays
npmat1 = np.array([narray])
npmat2 = np.array(nlist)

print(npmat1.shape)
print(npmat2.shape)

npmat3 = np.array([[1,2], [1,2]])
print(npmat3)


# transpose of matrix
print(npmat3.T)


# not that transpose doesnt affect the 1D array
nparray = np.array([1,2,3,4])
print(nparray.reshape(2, -1).T)

# norm of a vector
print(np.linalg.norm(nparray))

# dot rpoduct of the vector
print(np.sqrt(np.dot(nparray, nparray)))

# norm is nothing but sqrt of dot product of the vector itself

# mean

print(np.mean(nparray))

A = np.array([1, 2, 4]).reshape(-1,1)
B = np.array([4, 7, 3]).reshape(-1,1)

D = np.array([3,1, 4]).reshape(-1,1)

C = np.linalg.norm(A-B)
print(C)
print(np.linalg.norm(C-B))
print(np.linalg.norm(A-C))


A = np.array([1, 0, -1])
B = np.array([2, 8, 1])

cos_B = np.dot(A, B) / np.linalg.norm(A) * np.linalg.norm(B)

print(cos_B)

E = np.array([[2,2],[2,2]])
print(np.linalg.norm(E))


[1, 2, 3]
[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 1, 2, 3]
[2 4 6]
(1, 3)
(3,)
[[1 2]
 [1 2]]
[[1 1]
 [2 2]]
[[1 3]
 [2 4]]
5.477225575051661
5.477225575051661
2.5
5.916079783099616
3.653733169405061
6.570759700111196
5.873670062235365
4.0
